import type { Metadata } from "next";
import * as classname from "./layout.module.css";
import { StyleProvider } from "@/lib/styles/StyleProvider";
import  { Toaster } from 'react-hot-toast';

import "./global.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="dark">
      <body>
      <StyleProvider>
        <div className={classname.wrapper}>
          <div className={classname.container}>{children}</div>
        </div>
        <Toaster />
        </StyleProvider>
      </body>
    </html>
  );
}

