import type { Metadata } from "next";
import "./global.css";
import { css } from "styled-system/css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div className={Wrapper}>
          <div className={Inner}>{children}</div>
        </div>
      </body>
    </html>
  );
}

const Wrapper = css({
  display: "flex",
  justifyContent: "center",
});

const Inner = css({
  maxWidth: "430px",
});
